"""
Step 2: Load Parquet Data into DuckDB
=======================================
Reads the sample Parquet file and loads it into a DuckDB table called 'documents'.

Run: python scr_load_parquet_to_duckdb.py
Requires: scr_setup_and_create_data.py to have been run first.

Overview:
    This is the SECOND script in the RAG pipeline. It performs the following:
      1. Opens (or creates) a persistent DuckDB database file at db/rag.duckdb.
      2. Reads the Parquet file generated by Step 1 (data/sample_data.parquet).
      3. Creates a 'documents' table in DuckDB with all rows from the Parquet file.
      4. Verifies the load by printing schema info and sample rows.

    DuckDB's read_parquet() function provides zero-copy Parquet reading,
    making this step extremely fast even for larger datasets.

Dependencies:
    - os: For filesystem operations (directory creation, file existence checks).
    - duckdb: Embedded analytical database for storing and querying documents.
"""
import os      # Standard library: file/directory path operations
import duckdb  # Third-party: embedded OLAP database engine

# ── Configuration ──────────────────────────────────────────────────────────
# DB_PATH: File path for the persistent DuckDB database.
#          All pipeline tables (documents, chunks, embeddings) will live here.
DB_PATH      = "db/rag.duckdb"

# PARQUET_PATH: Path to the Parquet file created by scr_setup_and_create_data.py.
#               Contains structured rows with id, section, subsection, and text columns.
PARQUET_PATH = "data/sample_data.parquet"


def get_connection(db_path=DB_PATH):
    """Return a persistent DuckDB connection.

    Creates the parent directory for the database file if it does not exist,
    then opens a persistent DuckDB connection. A persistent connection means
    data is written to disk and survives across script runs.

    Args:
        db_path (str): File path where the DuckDB database will be stored.

    Returns:
        duckdb.DuckDBPyConnection: An open connection to the DuckDB database.
    """
    # Ensure the directory for the database file exists (e.g., 'db/')
    os.makedirs(os.path.dirname(db_path), exist_ok=True)
    # Open and return a persistent DuckDB connection (creates the file if needed)
    return duckdb.connect(db_path)


def load_parquet(con, parquet_path=PARQUET_PATH):
    """Load a Parquet file into a DuckDB table called 'documents'.

    Drops any existing 'documents' table (to allow re-runs), then creates
    a new table by reading all rows from the specified Parquet file using
    DuckDB's native read_parquet() function.

    Args:
        con (duckdb.DuckDBPyConnection): Active DuckDB connection.
        parquet_path (str): Path to the source Parquet file.

    Returns:
        int: The number of rows loaded into the 'documents' table.

    Raises:
        FileNotFoundError: If the Parquet file does not exist.
    """
    # Check that the Parquet file actually exists before attempting to load
    if not os.path.exists(parquet_path):
        raise FileNotFoundError(
            f"Parquet file not found: '{parquet_path}'. "
            f"Run scr_setup_and_create_data.py first."
        )

    # Drop the existing 'documents' table if it exists (idempotent re-run support)
    con.execute("DROP TABLE IF EXISTS documents")
    # Use DuckDB's read_parquet() to create the table directly from the Parquet file.
    # This is a CREATE TABLE AS SELECT (CTAS) pattern that reads and inserts in one step.
    con.execute(f"""
        CREATE TABLE documents AS
        SELECT * FROM read_parquet('{parquet_path}')
    """)

    # Query the row count to confirm successful loading
    count = con.execute("SELECT COUNT(*) FROM documents").fetchone()[0]
    print(f"  Loaded {count} rows into 'documents' table.")
    return count


def main():
    print("=" * 60)
    print("STEP 2: Load Parquet Data into DuckDB")
    print("=" * 60)

    # 1. Establish a persistent connection to the DuckDB database.
    #    This creates the database file if it doesn't already exist.
    print(f"\n[1/3] Connecting to DuckDB at '{DB_PATH}'...")
    con = get_connection()

    # 2. Read the Parquet file and load all rows into the 'documents' table.
    #    Any pre-existing 'documents' table is dropped first for idempotency.
    print(f"\n[2/3] Loading Parquet from '{PARQUET_PATH}'...")
    count = load_parquet(con, PARQUET_PATH)

    # 3. Verify the loaded data by printing a sample and schema information.
    #    This serves as a sanity check that the Parquet was read correctly.
    print(f"\n[3/3] Verifying loaded data...")
    # Fetch the first 5 rows as a pandas DataFrame for display
    df = con.execute("SELECT * FROM documents LIMIT 5").fetchdf()
    print(f"\n  First 5 rows:")
    print(df.to_string(max_colwidth=80))

    # Display the table schema (column names, types, nullable, etc.)
    # DESCRIBE is a DuckDB command similar to SQL's INFORMATION_SCHEMA
    schema = con.execute("DESCRIBE documents").fetchdf()
    print(f"\n  Table schema:")
    print(schema.to_string(index=False))

    # Final row count confirmation
    total = con.execute("SELECT COUNT(*) FROM documents").fetchone()[0]
    print(f"\n  Total rows in 'documents': {total}")

    # Close the DuckDB connection to flush any pending writes to disk
    con.close()

    print("\n" + "=" * 60)
    print("Parquet loaded! Next: python 3.scr_create_text_chunks.py")
    print("=" * 60)


if __name__ == "__main__":
    main()
